filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data/logs/*/*access.log

  json:
    keys_under_root: true
    overwrite_keys: true
    add_error_key: true
  fields:  
    topic: ak-access 
  tags: ["access"]
  close_inactive: 5m
  scan_frequency: 5s
  ignore_older: 24h
  clean_inactive: 36h

- type: log
  enabled: true
  paths:
    - /data/logs/*/*info.log

  json:
    keys_under_root: true
    overwrite_keys: true
    add_error_key: true
  fields:
    topic: ak-info
  tags: ["info"]
  close_inactive: 5m
  scan_frequency: 5s
  ignore_older: 24h
  clean_inactive: 36h


- type: log
  enabled: true
  paths:
    - /data/logs/*/*error.log
  json:
    keys_under_root: true
    overwrite_keys: true
    add_error_key: true
  fields:                                                               
    topic: ak-error
  tags: ["error"]
  close_inactive: 5m
  scan_frequency: 5s
  ignore_older: 24h
  clean_inactive: 36h


- type: log
  enabled: true
  paths:
    - /data/logs/*/*operator.log
  json:
    keys_under_root: true
    overwrite_keys: true
    add_error_key: true
  fields:
    topic: ak-operator
  tags: ["operator"]
  ignore_older: 24h
  clean_inactive: 36h


- type: log
  enabled: true
  paths:
    - /var/log/nginx/*access.log
  json:
    keys_under_root: true
    overwrite_keys: true
    add_error_key: true
  fields:
    topic: ak-nginx-access
  tags: ["nginx-access"]
  close_inactive: 5m
  scan_frequency: 5s
  ignore_older: 24h
  clean_inactive: 36h


- type: log
  enabled: true
  paths:
    - /var/log/nginx/*error.log 
  json:
    keys_under_root: true
    overwrite_keys: true
    add_error_key: true
  fields:
    topic: ak-nginx-error
  tags: ["nginx-error"]
  close_inactive: 5m
  scan_frequency: 5s
  ignore_older: 24h
  clean_inactive: 36h


output.kafka:
  enable: true
  hosts: ["xxxx"]
  topics:

    - topic: "ak-nginx-access"
      when.contains:
        tags: "nginx-access"
    - topic: "ak-nginx-error"
      when.contains:
        tags: "nginx-error"

    - topic: "ak_%{[business]}_access"
      when.contains:
        tags: "access"
    - topic: "ak_%{[business]}_info"
      when.contains:
        tags: "info"
    - topic: "ak_%{[business]}_error"
      when.contains:
        tags: "error"
    - topic: "ak_ak-global-log_operator"
      when.contains:
        tags: "operator"

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
processors: 
  - add_host_metadata:
      cache.ttl: 5m
  - timestamp:
      field: datetime 
      timezone: Asia/Shanghai
      layouts:
        - '2006-01-02 15:04:05'
        - '2006/01/02 15:04:05'
        - '2006-01-02 15:04:05.999'
        - '2006/01/02 15:04:05.999'
      test: 
        - '2019-06-22 16:33:51.111'

  - drop_fields:
      fields: 
      - ecs.version
      - host.mac
      - host.os.codename
      - host.os.family
      - host.os.kernel
      - host.os.name
      - host.os.platform
      - host.os.type
      - host.os.version
      - agent.name
      - host.architecture
      - host.name
      - host.id
       
      ignore_missing: false
  - decode_json_fields:
      document_id: "id"
      fields: ["datetime"]
      max_depth: 1
      target: ""
